post_install() {
	
	newversion=$1

	if [ ! -f /etc/xml/catalog ]; then
		xmlcatalog --noout --create /etc/xml/catalog
	fi

	xmlcatalog --noout --add "rewriteSystem" \
			   "http://docbook.sourceforge.net/release/xsl/$newversion" \
			   "/usr/share/xml/docbook/xsl-stylesheets-$newversion" \
		/etc/xml/catalog

	xmlcatalog --noout --add "rewriteURI" \
			   "http://docbook.sourceforge.net/release/xsl/$newversion" \
			   "/usr/share/xml/docbook/xsl-stylesheets-$newversion" \
		/etc/xml/catalog

	xmlcatalog --noout --add "rewriteSystem" \
			   "http://docbook.sourceforge.net/release/xsl/current" \
			   "/usr/share/xml/docbook/xsl-stylesheets-$newversion" \
		/etc/xml/catalog

	xmlcatalog --noout --add "rewriteURI" \
			   "http://docbook.sourceforge.net/release/xsl/current" \
			   "/usr/share/xml/docbook/xsl-stylesheets-$newversion" \
		/etc/xml/catalog
}

post_upgrade() {
	post_remove $2
	post_install $1
}

post_remove() {
	
	oldversion=$1

	xmlcatalog --noout --del "/usr/share/xml/docbook/xsl-stylesheets-$oldversion" /etc/xml/catalog
}
