#!/bin/bash -e

PORTPATH="kf5"
FRAMEWORK="https://download.kde.org/stable/plasma"

KF5VER=5.16.2

PKG=$(grep -R $FRAMEWORK . | cut -d / -f2)

for pkg in ${PKG[@]}
do
  [ -d $pkg ] || continue
  pushd $pkg >/dev/null
	echo "Update $pkg..."
    sed -i "s#version=.*#version=${KF5VER}#g" spkgbuild
    sed -i "/md5sum=(/,/)/d" spkgbuild
    pkgbuild -o
    pkgbuild -g >> spkgbuild
  popd >/dev/null
done
