pre_install() {
	getent group rsyncd >/dev/null || groupadd -g 48 rsyncd
	getent passwd rsyncd >/dev/null || useradd -c "rsyncd Daemon" -d /home/rsync -g rsyncd -s /bin/false -u 48 rsyncd
}

post_install() {
	msginfo
	msginfo "Enable and start rsyncd service:"
	msginfo "  ln -sv /etc/sv/rsyncd /var/service"
	msginfo
}

rm_sv() {
	rm -f /etc/sv/$1/supervise
	rm -f /var/service/$1
}

pre_remove() {
	rm_sv rsyncd
}
