pre_install() {
	getent group apache >/dev/null || groupadd -g 25 apache
	getent passwd apache >/dev/null || useradd -c "Apache Server" -d /srv/www -g apache -s /bin/false -u 25 apache
}

post_install() {
	msginfo
	msginfo "Enable and start httpd service:"
	msginfo "  ln -sv /etc/sv/httpd /var/service"
	msginfo
}

rm_sv() {
	rm -f /etc/sv/$1/supervise
	rm -f /var/service/$1
}

pre_remove() {
	rm_sv httpd
}
