pre_install() {
	getent group messagebus >/dev/null || groupadd -g 18 messagebus
	getent passwd messagebus >/dev/null || useradd -c "D-Bus Message Daemon User" -d /var/run/dbus -u 18 -g messagebus -s /bin/false messagebus
}

post_install() {
	dbus-uuidgen --ensure
	msginfo
	msginfo "Enable and start dbus service:"
	msginfo "  ln -sv /etc/sv/dbus /var/service"
	msginfo
}

rm_sv() {
	rm -f /etc/sv/$1/supervise
	rm -f /var/service/$1
}

pre_remove() {
	rm_sv dbus
}
