--- Makefile.sharedlibrary	2022-01-07 22:17:07.428464733 +0000
+++ Makefile	2022-01-07 22:03:53.498499145 +0000
@@ -45,7 +45,7 @@
 endif
 
 # Change to actual path for actual distribution packaging.
-INSTALL_PREFIX = /usr
+INSTALL_PREFIX = /usr/local
 
 # The 'noline' variant may be more appropriate for some distributions; it
 # doesn't have #line directives in the combined source.
@@ -72,18 +72,17 @@
 # Symlinks depend on platform conventions.
 .PHONY: install
 install: libduktape.$(SO_REALNAME_SUFFIX) libduktaped.$(SO_REALNAME_SUFFIX)
-	mkdir -p $(DESTDIR)${PREFIX}/lib/
-	mkdir -p ${DESTDIR}${PREFIX}/include
-	cp $+ $(DESTDIR)${PREFIX}/lib/
-	rm -f $(DESTDIR)${PREFIX}/lib/libduktape.so $(DESTDIR)${PREFIX}/lib/libduktape.$(SO_SONAME_SUFFIX)
-	ln -s libduktape.$(SO_REALNAME_SUFFIX) $(DESTDIR)${PREFIX}/lib/libduktape.so
-	ln -s libduktape.$(SO_REALNAME_SUFFIX) $(DESTDIR)${PREFIX}/lib/libduktape.$(SO_SONAME_SUFFIX)
-	rm -f $(INSTALL_PREFIX)/lib/libduktaped.so $(DESTDIR)${PREFIX}/lib/libduktaped.$(SO_SONAME_SUFFIX)
-	ln -s libduktaped.$(SO_REALNAME_SUFFIX) $(DESTDIR)${PREFIX}/lib/libduktaped.so
-	ln -s libduktaped.$(SO_REALNAME_SUFFIX) $(DESTDIR)${PREFIX}/lib/libduktaped.$(SO_SONAME_SUFFIX)
+	mkdir -p $(INSTALL_PREFIX)/lib/
+	cp $+ $(INSTALL_PREFIX)/lib/
+	rm -f $(INSTALL_PREFIX)/lib/libduktape.so $(INSTALL_PREFIX)/lib/libduktape.$(SO_SONAME_SUFFIX)
+	ln -s libduktape.$(SO_REALNAME_SUFFIX) $(INSTALL_PREFIX)/lib/libduktape.so
+	ln -s libduktape.$(SO_REALNAME_SUFFIX) $(INSTALL_PREFIX)/lib/libduktape.$(SO_SONAME_SUFFIX)
+	rm -f $(INSTALL_PREFIX)/lib/libduktaped.so $(INSTALL_PREFIX)/lib/libduktaped.$(SO_SONAME_SUFFIX)
+	ln -s libduktaped.$(SO_REALNAME_SUFFIX) $(INSTALL_PREFIX)/lib/libduktaped.so
+	ln -s libduktaped.$(SO_REALNAME_SUFFIX) $(INSTALL_PREFIX)/lib/libduktaped.$(SO_SONAME_SUFFIX)
 	mkdir -p $(INSTALL_PREFIX)/include/
-	cp $(DUKTAPE_SRCDIR)/duktape.h $(DUKTAPE_SRCDIR)/duk_config.h $(DESTDIR)${PREFIX}/include/
+	cp $(DUKTAPE_SRCDIR)/duktape.h $(DUKTAPE_SRCDIR)/duk_config.h $(INSTALL_PREFIX)/include/
 
 CCOPTS = -I./examples/cmdline
 duk:
-	$(CC) $(CCOPTS) -I$(DESTDIR)${PREFIX}/include -L$(DESTDIR)${PREFIX}/lib -Wall -Wextra -Os -o $@ ./examples/cmdline/duk_cmdline.c -lduktape -lm
+	$(CC) $(CCOPTS) -I$(INSTALL_PREFIX)/include -L$(INSTALL_PREFIX)/lib -Wall -Wextra -Os -o $@ ./examples/cmdline/duk_cmdline.c -lduktape -lm
