pre_install() {
	getent group ntp >/dev/null || groupadd -g 87 ntp
	getent passwd ntp >/dev/null || useradd -c "Network Time Protocol" -d /var/lib/ntp -u 87 -g ntp -s /bin/false ntp
}

post_install() {
	msginfo
	msginfo "Enable and start ntpd service:"
	msginfo "  ln -sv /etc/sv/ntpd /var/service"
	msginfo
}

rm_sv() {
	rm -f /etc/sv/$1/supervise
	rm -f /var/service/$1
}

pre_remove() {
	rm_sv ntpd
}
