pre_install() {
	getent group lpadmin >/dev/null || groupadd -g 19 lpadmin
	getent passwd lp >/dev/null || useradd -c "Print Service User" -d /var/spool/cups -g lp -s /bin/false -u 9 lp
}

post_install() {
	msginfo
	msginfo "Enable and start cupsd service:"
	msginfo "  ln -sv /etc/sv/cupsd /var/service"
	msginfo
}

rm_sv() {
	rm -f /etc/sv/$1/supervise
	rm -f /var/service/$1
}

pre_remove() {
	rm_sv cupsd
}
